name: Run Data Sync

on:
  workflow_dispatch:
    inputs:
      run_type:
        description: "Specify the run type"
        required: true
        default: "strava"
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master
    paths:
      - scripts/*.py
      - requirements.txt

env:
  RUN_TYPE: ${{ inputs.run_type }}
  ATHLETE: hadwin
  TITLE: hadwin Running
  MIN_GRID_DISTANCE: 5
  TITLE_GRID: Over 5km Runs
  GITHUB_NAME: hadwinn
  GITHUB_EMAIL: hadwin0119@outlook.com

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Set Variables
        id: set_variables
        run: |
          echo "PY=$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')" >> $GITHUB_ENV
          echo "PIP_CACHE=$(pip cache dir)" >> $GITHUB_ENV

      - name: Cache PIP
        uses: actions/cache@v2
        with:
          path: ${{ env.PIP_CACHE }}
          key: Ubuntu-pip-${{ env.PY }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sync Nike script
        if: ${{ env.RUN_TYPE == 'nike' }}
        run: |
          python scripts/nike_sync.py ${{ secrets.NIKE_REFRESH_TOKEN }}

      # (其余脚本步骤保持不变，优化 if 条件语法)
